import asyncio
import hashlib
import json
import math
import time
from dataclasses import asdict
from decimal import Decimal, ROUND_DOWN, ROUND_UP
from app.models import Signal, Position, MarketRules
from app.paper import PaperBroker
from app.risk import RiskEngine
from .bridge_client import BridgeError


def client_id(*parts):
    return 'sol'+hashlib.sha256(':'.join(map(str, parts)).encode()).hexdigest()[:29]


class ExecutionEngine:
    def __init__(self, config, portfolio, audit, alerts=None, bridge=None, state_provider=None, clock=time.time):
        if config.dry_run and bridge is not None:
            raise ValueError('Dry run cannot have a live execution client')
        if not config.dry_run and bridge is None:
            raise ValueError('Live execution bridge required')
        self.config, self.portfolio, self.audit = config, portfolio, audit
        self._dry_run = config.dry_run
        self.instance_id = portfolio.get_meta('instance_id')
        if not self.instance_id or portfolio.get_meta('mode') != ('paper' if self._dry_run else 'live'):
            raise ValueError('Execution requires its current isolated instance and matching ledger mode')
        self.alerts, self.bridge, self.state_provider, self.clock = alerts, bridge, state_provider, clock
        self.paper = PaperBroker(config.risk.taker_fee_rate, config.risk.slippage_bps)
        self.risk = RiskEngine(config, audit)
        self.rules = MarketRules()
        self.lock = asyncio.Lock()
        self.paused = bool(portfolio.get_meta('paused', False))
        self.halt_reason = portfolio.get_meta('halt_reason', '')
        self.ready = config.dry_run

    async def _bridge_call(self, operation, **payload):
        # Guard every call, including reads and callers that mutate .bridge later.
        if self._dry_run or self.config.dry_run is not False or not self.bridge \
                or self.portfolio.get_meta('mode') != 'live' \
                or self.portfolio.get_meta('instance_id') != self.instance_id \
                or self.config.live.enabled is not True or self.config.live.dedicated_account_confirmed is not True \
                or self.config.live.confirmation != 'ENABLE_SMALL_CAPITAL_LIVE':
            raise BridgeError('Private access from a paper or mismatched instance is forbidden',
                              code='EXECUTION_ISOLATION_VIOLATION')
        return await self.bridge.call(operation, **payload)

    def _client_id(self, *parts):
        return client_id(self.instance_id, *parts)

    def _prepare(self, oid, kind, position_id, payload, now, *, identity_parts):
        if oid != self._client_id(*identity_parts):
            raise ValueError('Order identity must be generated by this instance')
        payload = {**payload, '_owner': {'instance_id': self.instance_id, 'version': 1,
                                       'identity_parts': list(identity_parts), 'symbol': self.config.trade_symbol}}
        prepared = self.portfolio.prepare(oid, kind, position_id, payload, now)
        if prepared:
            self.audit.emit('order_prepared', client_id=oid, order_kind=kind, position_id=position_id,
                            quantity=payload.get('quantity'), mode='paper' if self._dry_run else 'live')
        return prepared

    def _owned_order(self, oid, kind=None):
        order = self.portfolio.order(oid)
        owner = order['payload'].get('_owner', {}) if order else {}
        if (not order or owner.get('instance_id') != self.instance_id or owner.get('version') != 1
                or owner.get('symbol') != self.config.trade_symbol or not isinstance(owner.get('identity_parts'), list)
                or oid != self._client_id(*owner['identity_parts']) or (kind and order['kind'] != kind)):
            return None
        return order

    def _owned_position(self, position_id):
        p = self.portfolio.position(position_id)
        entry = self._owned_order(self._client_id(position_id, 'entry'), 'ENTRY')
        signal = entry['payload'].get('signal', {}) if entry else {}
        if (not p or not entry or signal.get('id') != p.id or signal.get('symbol') != p.symbol
                or signal.get('side') != p.side or p.symbol != self.config.trade_symbol
                or not all(math.isfinite(v) and v > 0 for v in (p.quantity, p.initial_quantity, p.entry_price))
                or p.quantity > p.initial_quantity + 1e-12
                or abs(entry['applied_qty'] - p.initial_quantity) > float(self.rules.step_size)/2):
            return None
        return p

    async def _verify_position_ownership(self, position_id):
        p = self._owned_position(position_id)
        if not p:
            self.halt('UNOWNED_POSITION_NO_AUTOMATIC_ACTION')
            return None
        if self._dry_run:
            return p
        try:
            positions = await self._bridge_call('positions')
            opens = await self._bridge_call('open_orders')
            stops = await self._bridge_call('open_stops')
            if not all(isinstance(x, list) for x in (positions, opens, stops)):
                raise BridgeError('Malformed ownership snapshot')
            matching = [x for x in positions if x.get('symbol') == p.symbol and float(x.get('positionAmt', 0)) != 0]
            expected = p.quantity * (1 if p.side == 'LONG' else -1)
            if (len(matching) != 1 or matching[0].get('positionSide', 'BOTH') != 'BOTH'
                    or not math.isfinite(float(matching[0]['positionAmt']))
                    or abs(float(matching[0]['positionAmt']) - expected) > float(self.rules.step_size)/2):
                self.halt('EXTERNAL_POSITION_OR_UNAPPLIED_FILL_NO_AUTOMATIC_ACTION')
                return None
            for row in opens:
                if row.get('symbol') == p.symbol and not self._owned_order(row.get('clientOrderId', '')):
                    self.halt('EXTERNAL_ORDER_NO_AUTOMATIC_ACTION')
                    return None
            for row in stops:
                if row.get('symbol') == p.symbol and not self._owned_order(row.get('clientAlgoId', ''), 'STOP'):
                    self.halt('EXTERNAL_STOP_NO_AUTOMATIC_ACTION')
                    return None
            return p
        except BridgeError as error:
            self.halt('OWNERSHIP_UNCONFIRMED_NO_AUTOMATIC_ACTION')
            self.notify('api_error', operation='ownership_check', message=str(error))
            return None

    def notify(self, kind, **payload):
        self.audit.emit(kind, **payload)
        if self.alerts:
            self.alerts.notify(kind, payload)

    def halt(self, reason):
        if reason != self.halt_reason:
            self.halt_reason = reason
            self.portfolio.set_meta('halt_reason', reason)
            self.notify('circuit_breaker', reason=reason)

    async def initialize(self):
        if self.config.dry_run:
            for order in self.portfolio.pending():
                if not self._owned_order(order['client_id']):
                    self.halt('UNOWNED_LEDGER_ORDER_NO_IMPORT')
                    continue
                if order['kind'] == 'ENTRY':
                    self.portfolio.update_order(order['client_id'], 'CANCELED')
                    self.notify('order_canceled', client_id=order['client_id'], reason='paper_restart_cancels_unfilled')
            return
        mode = await self._bridge_call('position_mode')
        if mode.get('dualSidePosition') not in (False, 'false'):
            self.halt('DEDICATED_ONE_WAY_ACCOUNT_REQUIRED')
            return
        raw = await self._bridge_call('rules', symbol=self.config.trade_symbol, order_type=self.config.execution.entry_order_type)
        self.rules = self.parse_rules(raw)
        await self.refresh_account()
        await self.reconcile()
        await self.audit_external_state()
        self.ready = not self.halt_reason

    @staticmethod
    def parse_rules(raw):
        if 'filters' in raw:
            filters = {x['filterType']: x for x in raw['filters']}
            lot = filters.get('MARKET_LOT_SIZE') or filters['LOT_SIZE']
            if float(lot.get('stepSize', 0)) <= 0:
                lot = filters['LOT_SIZE']
            return MarketRules(lot['stepSize'], filters['PRICE_FILTER']['tickSize'], float(lot['minQty']),
                               float(filters.get('MIN_NOTIONAL', {}).get('notional', 5)))
        return MarketRules(str(raw.get('stepSize', raw.get('step_size', '.001'))),
                           str(raw.get('tickSize', raw.get('tick_size', '.01'))),
                           float(raw.get('minQty', raw.get('min_qty', .001))),
                           float(raw.get('minNotional', raw.get('min_notional', 5))))

    async def refresh_account(self):
        if not self.bridge:
            return
        account = await self._bridge_call('account')
        balance = float(account['totalWalletBalance'])
        equity = float(account.get('totalMarginBalance', balance))
        available = float(account['availableBalance'])
        if not all(math.isfinite(x) for x in (balance, equity, available)) or equity <= 0:
            raise BridgeError('Invalid account snapshot')
        self.portfolio.set_meta('exchange_balance', balance)
        self.portfolio.set_meta('exchange_available', available)
        if equity > self.config.live.max_account_equity_usdt:
            self.halt('SMALL_CAPITAL_ACCOUNT_LIMIT')
        self.audit.emit('account_snapshot', balance=balance, equity=equity, available=available)

    async def audit_external_state(self):
        if not self.bridge:
            return
        positions = await self._bridge_call('positions')
        opens = await self._bridge_call('open_orders')
        stops = await self._bridge_call('open_stops')
        if not all(isinstance(x, list) for x in (positions, opens, stops)):
            raise BridgeError('Malformed positions/order snapshot')
        local = {p.symbol: p for p in self.portfolio.positions()}
        for p in positions:
            amount = float(p.get('positionAmt', 0))
            if amount == 0:
                continue
            candidate = local.get(p['symbol'])
            owned = self._owned_position(candidate.id) if candidate else None
            if not owned or owned.side != ('LONG' if amount > 0 else 'SHORT') or abs(abs(amount)-owned.quantity) > float(self.rules.step_size)/2:
                self.halt('EXTERNAL_POSITION_OR_UNAPPLIED_FILL')
        for o in opens:
            if not self._owned_order(o.get('clientOrderId', '')):
                self.halt('EXTERNAL_OPEN_ORDER')
        for o in stops:
            if not self._owned_order(o.get('clientAlgoId', ''), 'STOP'):
                self.halt('EXTERNAL_CONDITIONAL_ORDER')

    async def submit(self, signal, market):
        first = self.risk.assess(signal, market, self.portfolio, self.rules, self.clock(),
                                 paused=self.paused, halt_reason=self.halt_reason)
        if not first.allowed:
            return first
        async with self.lock:
            now = self.clock()
            market = self.state_provider() if self.state_provider else market
            # Normalize protection before sizing; never silently increase quantity to minimum notional.
            step = Decimal(self.rules.tick_size)
            if signal.order_type == 'LIMIT':
                signal.entry_price = float((Decimal(str(signal.entry_price))/step).to_integral_value(
                    rounding=ROUND_DOWN if signal.side == 'LONG' else ROUND_UP)*step)
            signal.stop_price = float((Decimal(str(signal.stop_price))/step).to_integral_value(
                rounding=ROUND_DOWN if signal.side == 'LONG' else ROUND_UP)*step)
            if self.bridge:
                await self.refresh_account()
                await self.audit_external_state()
            second = self.risk.assess(signal, market, self.portfolio, self.rules, now,
                                      paused=self.paused, halt_reason=self.halt_reason or ('' if self.ready else 'STARTUP_RECONCILING'))
            if not second.allowed:
                return second
            oid = self._client_id(signal.id, 'entry')
            payload = {'signal': asdict(signal), 'quantity': second.quantity}
            if not self._prepare(oid, 'ENTRY', signal.id, payload, now, identity_parts=(signal.id, 'entry')):
                self.audit.emit('duplicate_signal', signal_id=signal.id, client_id=oid)
                return None
            if not self.bridge:
                fill = self.paper.fill(market, 'BUY' if signal.side == 'LONG' else 'SELL', second.quantity,
                                       signal.order_type, signal.entry_price)
                self.audit.emit('paper_order_submitted', client_id=oid, order_type=signal.order_type,
                                quantity=second.quantity, price=signal.entry_price)
                if fill:
                    self._apply_entry(oid, fill, now)
                else:
                    self.portfolio.update_order(oid, 'NEW')
                    self.notify('order_submitted', client_id=oid, mode='paper', status='NEW')
                return second
            self.portfolio.update_order(oid, 'SUBMITTING')
            try:
                await self._bridge_call('leverage', symbol=signal.symbol, leverage=self.config.execution.leverage)
                # No other entry can interleave (lock). Last policy read is done again by bridge before POST.
                response = await self._bridge_call('place_order', symbol=signal.symbol,
                    side='BUY' if signal.side == 'LONG' else 'SELL', type=signal.order_type,
                    quantity=str(second.quantity), price=str(signal.entry_price) if signal.order_type == 'LIMIT' else None,
                    client_id=oid, reduce_only=False,
                    risk_context={'entry_price': market.price, 'stop_price': signal.stop_price,
                                  'max_loss_usdt': second.max_loss, 'equity': self.portfolio.metrics(now)['equity'],
                                  'leverage': self.config.execution.leverage})
                self.notify('order_submitted', client_id=oid, response=response)
                await self._consume_order(oid, response)
            except BridgeError as error:
                self.portfolio.update_order(oid, 'UNKNOWN' if error.ambiguous else 'REJECTED')
                self.notify('api_error', client_id=oid, code=error.code, message=str(error), ambiguous=error.ambiguous)
                if error.ambiguous:
                    self.halt('UNKNOWN_ORDER_RECONCILIATION_REQUIRED')
                    await self._query_order(oid)
            return second

    def _apply_entry(self, oid, fill, now):
        order = self._owned_order(oid, 'ENTRY')
        if not order:
            raise BridgeError('Cannot apply an unowned entry', ambiguous=True, code='UNOWNED_ORDER')
        signal = Signal(**order['payload']['signal'])
        total, price, total_fee = float(fill['executedQty']), float(fill['avgPrice']), float(fill.get('fee', 0))
        delta = total-order['applied_qty']
        if delta <= 1e-12:
            self.portfolio.update_order(oid, fill['status'])
            return
        if not all(math.isfinite(v) and v >= 0 for v in (delta, total_fee)) or price <= 0:
            raise BridgeError('Invalid fill amounts')
        position = self.portfolio.position(order['position_id'])
        if position and not self._owned_position(position.id):
            self.halt('UNOWNED_POSITION_NO_AUTOMATIC_ACTION')
            raise BridgeError('Existing position has no owned confirmed entry', ambiguous=True)
        if not position:
            position = Position(signal.id, signal.strategy, signal.symbol, signal.side, price, 0, 0,
                                signal.stop_price, signal.take_profits, now, self.config.execution.leverage)
        # Binance avgPrice is cumulative; subtract prior cumulative notional before applying delta.
        old_notional = position.entry_price*position.initial_quantity
        position.entry_price = (old_notional + total*price-order['applied_qty']*position.entry_price)/(position.initial_quantity+delta)
        position.quantity += delta
        position.initial_quantity += delta
        fee_delta = max(0, total_fee-order['applied_fee'])
        position.fees += fee_delta
        position.stop_status = 'ACTIVE' if self.config.dry_run else 'PENDING'
        self.portfolio.db.execute('BEGIN IMMEDIATE')
        try:
            self.portfolio.save_position(position)
            self.portfolio.add_cash(f'{oid}:{total}:fee', -fee_delta, now)
            self.portfolio.update_order(oid, fill['status'], total, total_fee)
            self.portfolio.db.execute('COMMIT')
        except BaseException:
            self.portfolio.db.execute('ROLLBACK')
            raise
        self.notify('position_opened', position=position.to_dict(), fill_quantity=delta, mode='paper' if self.config.dry_run else 'live')

    async def _consume_order(self, oid, response):
        order = self._owned_order(oid)
        if not order or order['kind'] not in ('ENTRY', 'EXIT'):
            self.halt('UNOWNED_ORDER_RESPONSE_NO_IMPORT')
            raise BridgeError('Refusing an order absent from this instance ledger', ambiguous=True, code='UNOWNED_ORDER')
        if not isinstance(response, dict):
            raise BridgeError('Malformed order response', ambiguous=True)
        signal = order['payload'].get('signal', {})
        position = self.portfolio.position(order['position_id'])
        side = signal.get('side') if order['kind'] == 'ENTRY' else position.side if position else order['payload'].get('position_side')
        expected_side = ('BUY' if side == 'LONG' else 'SELL') if order['kind'] == 'ENTRY' else ('SELL' if side == 'LONG' else 'BUY')
        if order['payload'].get('native_exchange_order_id') or order['payload'].get('parent_stop_id'):
            self.halt('NATIVE_STOP_CHILD_RECONCILIATION_NOT_ACCEPTED')
            raise BridgeError('Native-stop child adoption is not accepted in this isolation iteration', ambiguous=True)
        matches_identity = response.get('clientOrderId') == oid
        if side not in ('LONG', 'SHORT') or not matches_identity or response.get('symbol') != self.config.trade_symbol or response.get('side') != expected_side:
            self.halt('ORDER_IDENTITY_MISMATCH_NO_IMPORT')
            raise BridgeError('Exchange response does not match the owned original order', ambiguous=True, code='ORDER_IDENTITY_MISMATCH')
        status = response.get('status', 'UNKNOWN')
        if status not in ('NEW', 'PARTIALLY_FILLED', 'FILLED', 'CANCELED', 'EXPIRED', 'REJECTED', 'EXPIRED_IN_MATCH'):
            raise BridgeError('Unknown exchange order status', ambiguous=True)
        qty = float(response.get('executedQty', 0))
        if not math.isfinite(qty) or qty < order['applied_qty'] or qty > float(order['payload']['quantity']) + float(self.rules.step_size)/2:
            raise BridgeError('Invalid cumulative owned fill quantity', ambiguous=True)
        if qty > order['applied_qty']:
            price = float(response.get('avgPrice', 0))
            if (not math.isfinite(price) or price <= 0) and float(response.get('cumQuote', 0)) > 0:
                price = float(response['cumQuote']) / qty
            if not math.isfinite(price) or price <= 0 or not response.get('orderId'):
                raise BridgeError('Confirmed order needs an authoritative average price and exchange ID', ambiguous=True)
            # Confirmed exposure receives protection before any optional fee/history request.
            # Unresolved fees remain explicit and do not masquerade as reconciled zero fees.
            fees_pending = self.portfolio.get_meta('fee_pending_orders', {})
            fees_pending[oid] = {'exchange_order_id': str(response['orderId']), 'quantity': qty}
            self.portfolio.set_meta('fee_pending_orders', fees_pending)
            fill = {'status': status, 'executedQty': qty, 'avgPrice': price,
                    'fee': order['applied_fee']}
            if order['kind'] == 'ENTRY':
                self._apply_entry(oid, fill, self.clock())
                await self._protect(order['position_id'])
                if status in ('NEW', 'PARTIALLY_FILLED'):
                    # Freeze partial entry rather than permit unprotected future limit fills.
                    await self._cancel(oid)
            else:
                self._apply_exit(oid, fill, self.clock())
        else:
            self.portfolio.update_order(oid, status)
        await self._reconcile_fees(oid)

    async def _reconcile_fees(self, oid):
        pending = self.portfolio.get_meta('fee_pending_orders', {})
        item = pending.get(oid)
        order = self._owned_order(oid)
        if not item or not order:
            return
        try:
            if item.get('lookup_client_id', oid) != oid:
                raise BridgeError('Fee query has no owned original client ID', ambiguous=True)
            trades = await self._bridge_call('trades', symbol=self.config.trade_symbol, client_id=oid)
            if not isinstance(trades, list) or not trades:
                raise BridgeError('Trade fee evidence is not available', ambiguous=True)
            if any(str(t.get('orderId')) != item['exchange_order_id'] or t.get('symbol') != self.config.trade_symbol
                   or t.get('commissionAsset') != 'USDT' for t in trades):
                raise BridgeError('Trade fee evidence identity or asset mismatch', ambiguous=True)
            filled = sum(float(t['qty']) for t in trades)
            fee = sum(float(t['commission']) for t in trades)
            if not math.isfinite(filled) or not math.isfinite(fee) or fee < 0 or abs(filled - item['quantity']) > float(self.rules.step_size)/2:
                raise BridgeError('Trade fee evidence incomplete', ambiguous=True)
            delta = fee - order['applied_fee']
            if delta < -1e-12:
                raise BridgeError('Trade fee evidence regressed', ambiguous=True)
            self.portfolio.db.execute('BEGIN IMMEDIATE')
            try:
                p = self.portfolio.position(order['position_id'])
                if p:
                    p.fees += delta
                    self.portfolio.save_position(p)
                else:
                    row = self.portfolio.db.execute('SELECT data FROM trades WHERE id=?', (order['position_id'],)).fetchone()
                    if row:
                        trade = json.loads(row[0])
                        trade['fees'] += delta
                        trade['net_pnl'] -= delta
                        trade['pnl'] -= delta
                        self.portfolio.db.execute('UPDATE trades SET data=? WHERE id=?',
                                                 (json.dumps(trade, allow_nan=False), order['position_id']))
                self.portfolio.add_cash(f'{oid}:{fee}:fee_reconciled', -delta, self.clock())
                self.portfolio.update_order(oid, order['status'], applied_fee=fee)
                pending.pop(oid, None)
                self.portfolio.set_meta('fee_pending_orders', pending)
                self.portfolio.db.execute('COMMIT')
            except BaseException:
                self.portfolio.db.execute('ROLLBACK')
                raise
            self.audit.emit('fill_fees_reconciled', client_id=oid, fee=fee)
        except (BridgeError, TypeError, ValueError, KeyError) as error:
            if not self.halt_reason:
                self.halt('FILL_FEES_RECONCILIATION_REQUIRED')
            self.notify('api_error', client_id=oid, operation='fees_after_protection', message=str(error))

    async def _protect(self, position_id):
        if not self.bridge:
            return
        p = await self._verify_position_ownership(position_id)
        if not p:
            return
        sid = self._client_id(p.id, 'stop', p.initial_quantity)
        if p.stop_status == 'ACTIVE' and p.stop_id == sid:
            return
        old_stop = p.stop_id
        prepared = self._prepare(sid, 'STOP', p.id, {'quantity': p.quantity}, self.clock(),
                                 identity_parts=(p.id, 'stop', p.initial_quantity))
        if not self._owned_order(sid, 'STOP'):
            self.halt('UNOWNED_STOP_NO_AUTOMATIC_ACTION')
            return
        try:
            if prepared:
                self.portfolio.update_order(sid, 'SUBMITTING')
                await self._bridge_call('stop', symbol=p.symbol, side='SELL' if p.side == 'LONG' else 'BUY',
                                       stop_price=str(p.stop_price), quantity=str(p.quantity), client_id=sid)
            stop = await self._bridge_call('query_stop', symbol=p.symbol, client_id=sid)
            if (not stop or stop.get('algoStatus') not in ('NEW', 'WORKING')
                    or stop.get('clientAlgoId') != sid or stop.get('symbol') != p.symbol
                    or stop.get('side') != ('SELL' if p.side == 'LONG' else 'BUY')):
                raise BridgeError('Stop protection not confirmed', ambiguous=True)
            p.stop_id, p.stop_status = sid, 'ACTIVE'
            self.portfolio.save_position(p)
            self.portfolio.update_order(sid, 'PROTECTED')
            if old_stop and old_stop != sid:
                await self._cancel_stop(old_stop, p.symbol)
            self.notify('stop_confirmed', position_id=p.id, client_id=sid)
        except Exception as error:
            self.portfolio.update_order(sid, 'STOP_UNKNOWN')
            p.stop_id, p.stop_status = sid, 'FAILED'
            self.portfolio.save_position(p)
            self.halt('STOP_FAILED_EMERGENCY_EXIT')
            self.notify('stop_failed', position_id=p.id, message=str(error))
            # Any unfinished entry must first be canceled; reduceOnly market exit follows immediately.
            for entry in self.portfolio.pending():
                if entry['kind'] == 'ENTRY' and entry['position_id'] == p.id:
                    await self._cancel(entry['client_id'])
            await self._close_unlocked(p, 'stop_failed', 1)

    def _apply_exit(self, oid, fill, now):
        order = self._owned_order(oid, 'EXIT')
        if not order:
            raise BridgeError('Cannot apply an unowned exit', ambiguous=True, code='UNOWNED_ORDER')
        p = self._owned_position(order['position_id'])
        total, total_fee = float(fill['executedQty']), float(fill.get('fee', 0))
        delta = total-order['applied_qty']
        if delta <= 1e-12:
            self.portfolio.update_order(oid, fill['status'])
            return
        if not p:
            self.halt('UNOWNED_POSITION_NO_AUTOMATIC_ACTION')
            raise BridgeError('Exit cannot change an unowned position', ambiguous=True)
        if delta > p.quantity+float(self.rules.step_size)/2:
            self.halt('EXIT_FILL_EXCEEDS_OWNERSHIP')
            return
        price = float(fill['avgPrice'])
        fee = max(0, total_fee-order['applied_fee'])
        gross = (price-p.entry_price)*delta*(1 if p.side == 'LONG' else -1)
        p.realized_pnl += gross
        p.fees += fee
        p.quantity = max(0, p.quantity-delta)
        reason = order['payload']['reason']
        if self._dry_run and reason.startswith('take_profit_') and total >= order['payload']['quantity'] - 1e-12:
            index = int(reason.rsplit('_', 1)[1]) - 1
            if index not in p.tp_completed:
                p.tp_completed.append(index)
            # TP completion and cash/quantity application share the same transaction.
            # A restart between fill and the caller returning must not sell TP1 twice.
        self.portfolio.db.execute('BEGIN IMMEDIATE')
        try:
            self.portfolio.add_cash(f'{oid}:{total}:exit', gross-fee, now)
            self.portfolio.update_order(oid, fill['status'], total, total_fee)
            if p.quantity <= 1e-12:
                self.portfolio.closed(p, price, now, reason)
            else:
                self.portfolio.save_position(p)
            self.portfolio.db.execute('COMMIT')
        except BaseException:
            self.portfolio.db.execute('ROLLBACK')
            raise
        self.notify('position_closed' if p.quantity <= 1e-12 else 'position_reduced',
                    position_id=p.id, quantity=delta, price=price, pnl=gross-fee, reason=reason)

    async def _close_unlocked(self, p, reason, fraction=1, market=None):
        p = await self._verify_position_ownership(p.id)
        if not p:
            return
        if any(o['kind'] == 'EXIT' and o['position_id'] == p.id for o in self.portfolio.pending()):
            return
        quantity = p.quantity if fraction >= 1 else float((Decimal(str(p.initial_quantity*fraction))/Decimal(self.rules.step_size)).to_integral_value(rounding=ROUND_DOWN)*Decimal(self.rules.step_size))
        quantity = min(quantity, p.quantity)
        if quantity <= 0:
            self.audit.emit('exit_dust_deferred', position_id=p.id, reason=reason)
            return
        oid = self._client_id(p.id, reason, p.quantity)
        if not self._prepare(oid, 'EXIT', p.id, {'quantity': quantity, 'reason': reason, 'position_side': p.side},
                             self.clock(), identity_parts=(p.id, reason, p.quantity)):
            return
        self.portfolio.update_order(oid, 'SUBMITTING')
        if not self.bridge:
            fill = self.paper.fill(market, 'SELL' if p.side == 'LONG' else 'BUY', quantity)
            self.audit.emit('paper_order_submitted', client_id=oid, order_type='MARKET',
                            quantity=quantity, reason=reason)
            self._apply_exit(oid, fill, self.clock())
            return
        try:
            response = await self._bridge_call('place_order', symbol=p.symbol, side='SELL' if p.side == 'LONG' else 'BUY',
                type='MARKET', quantity=str(quantity), client_id=oid, reduce_only=True)
            await self._consume_order(oid, response)
            if not self.portfolio.position(p.id) and p.stop_id:
                await self._cancel_stop(p.stop_id, p.symbol)
        except BridgeError as error:
            self.portfolio.update_order(oid, 'UNKNOWN' if error.ambiguous else 'REJECTED')
            self.halt('EXIT_NOT_CONFIRMED')
            self.notify('api_error', client_id=oid, message=str(error), ambiguous=error.ambiguous)

    async def on_market(self, market, protection_market=None):
        protection_market = protection_market or market
        if protection_market.stale or protection_market.price <= 0 or not math.isfinite(protection_market.price):
            return
        async with self.lock:
            if self.config.dry_run:
                for order in self.portfolio.pending():
                    if not self._owned_order(order['client_id']):
                        self.halt('UNOWNED_LEDGER_ORDER_NO_IMPORT')
                        continue
                    if order['kind'] != 'ENTRY':
                        continue
                    signal = Signal(**order['payload']['signal'])
                    if self.clock()-order['created_at'] > self.config.execution.limit_expiry_seconds:
                        await self._cancel(order['client_id'])
                        continue
                    decision = self.risk.assess(signal, market, self.portfolio, self.rules, self.clock(),
                        paused=self.paused, halt_reason=self.halt_reason or ('' if self.ready else 'PUBLIC_RULES_PENDING'), own_pending=True)
                    if not decision.allowed or decision.quantity < order['payload']['quantity']:
                        await self._cancel(order['client_id'])
                        continue
                    fill = self.paper.fill(market, 'BUY' if signal.side == 'LONG' else 'SELL',
                                           order['payload']['quantity'], 'LIMIT', signal.entry_price)
                    if fill:
                        self._apply_entry(order['client_id'], fill, self.clock())
            market = protection_market
            for p in self.portfolio.positions():
                direction = 1 if p.side == 'LONG' else -1
                # Public depth and last trades arrive independently. Use the
                # conservative executable side so a new gapped book cannot
                # turn an old high ticker into a bogus "take profit" fill.
                trigger_price = (min(market.price, market.bid or market.price) if p.side == 'LONG'
                                 else max(market.price, market.ask or market.price)) if self._dry_run else market.price
                if (trigger_price-p.stop_price)*direction <= 0:
                    if self.config.dry_run:
                        self.notify('stop_triggered', position_id=p.id)
                        await self._close_unlocked(p, 'stop_loss', market=market)
                    # Live SL is exchange-native; reconcile it rather than racing with a second close.
                    continue
                for index, target in enumerate(p.take_profits):
                    if index in p.tp_completed or index in p.tp_deferred or (trigger_price-float(target['price']))*direction < 0:
                        continue
                    before = self.portfolio.position(p.id)
                    if not before:
                        break
                    # Final TP closes all owned remainder, including rounding dust.
                    fraction = 1 if self.config.dry_run and index == len(p.take_profits)-1 else float(target['fraction'])
                    if self._dry_run and fraction < 1 and before.initial_quantity*fraction < float(self.rules.step_size):
                        before.tp_deferred.append(index)
                        self.portfolio.save_position(before)
                        self.audit.emit('paper_tp_dust_deferred_to_final', position_id=p.id, target=index+1)
                        continue
                    await self._close_unlocked(before, f'take_profit_{index+1}', fraction, market)
                    current = self.portfolio.position(p.id)
                    if current and current.quantity < before.quantity - 1e-12:
                        if index not in current.tp_completed:
                            current.tp_completed.append(index)
                        self.portfolio.save_position(current)
                    elif current:
                        # No confirmed reduction: never claim this TP was executed.
                        break
                    else:
                        break
                    if not self.config.dry_run:
                        break  # Keep the sealed live/reconciliation path unchanged.

    async def expire_paper_entries(self):
        if not self._dry_run:
            return
        async with self.lock:
            for order in self.portfolio.pending():
                if order['kind'] == 'ENTRY' and (self.paused or self.halt_reason or not self.ready
                        or self.clock() - order['created_at'] > self.config.execution.limit_expiry_seconds):
                    await self._cancel(order['client_id'])

    async def _cancel(self, oid):
        order = self._owned_order(oid)
        if not order:
            self.halt('UNOWNED_CANCEL_NO_AUTOMATIC_ACTION')
            return
        if self.config.dry_run:
            self.portfolio.update_order(oid, 'CANCELED')
        else:
            if order['status'] in ('UNKNOWN', 'SUBMITTING'):
                await self._query_order(oid)
                order = self._owned_order(oid)
                if not order or order['status'] not in ('NEW', 'PARTIALLY_FILLED'):
                    return
            try:
                result = await self._bridge_call('cancel_order', symbol=self.config.trade_symbol, client_id=oid)
                # Fills may race cancellation; consume exact cumulative fills on next reconciliation.
                if float(result.get('executedQty', 0)) > order['applied_qty']:
                    self.portfolio.update_order(oid, 'UNKNOWN')
                else:
                    self.portfolio.update_order(oid, result.get('status', 'UNKNOWN'))
            except BridgeError as error:
                self.portfolio.update_order(oid, 'UNKNOWN')
                self.halt('CANCEL_UNCONFIRMED')
                self.notify('api_error', client_id=oid, message=str(error))
        self.notify('order_canceled', client_id=oid, status=self.portfolio.order(oid)['status'])

    async def cancel_order(self, oid):
        async with self.lock:
            await self._cancel(oid)

    async def _cancel_stop(self, sid, symbol):
        order = self._owned_order(sid, 'STOP')
        if not order or symbol != self.config.trade_symbol:
            self.halt('UNOWNED_STOP_CANCEL_NO_AUTOMATIC_ACTION')
            return
        try:
            await self._bridge_call('cancel_stop', symbol=symbol, client_id=sid)
            self.portfolio.update_order(sid, 'CANCELED')
            self.notify('order_canceled', client_id=sid, conditional=True)
        except BridgeError as error:
            self.portfolio.update_order(sid, 'STOP_UNKNOWN')
            self.halt('STOP_CANCEL_UNCONFIRMED')
            self.notify('api_error', client_id=sid, message=str(error))

    async def _query_order(self, oid):
        if not self._owned_order(oid):
            self.halt('UNOWNED_RECONCILIATION_NO_IMPORT')
            return
        try:
            result = await self._bridge_call('order', symbol=self.config.trade_symbol, client_id=oid)
            if result:
                await self._consume_order(oid, result)
            else:
                self.halt('UNKNOWN_ORDER_NOT_FOUND_NO_BLIND_RETRY')
        except BridgeError as error:
            self.notify('api_error', client_id=oid, message=str(error), operation='reconcile')

    async def reconcile(self):
        if not self.bridge:
            return
        async with self.lock:
            for order in self.portfolio.pending():
                if not self._owned_order(order['client_id']):
                    self.halt('UNOWNED_LEDGER_ORDER_NO_IMPORT')
                    continue
                if order['kind'] == 'STOP':
                    continue
                await self._query_order(order['client_id'])
                fresh = self.portfolio.order(order['client_id'])
                if fresh['kind'] == 'ENTRY' and fresh['status'] in ('NEW', 'PARTIALLY_FILLED') and self.clock()-fresh['created_at'] > self.config.execution.limit_expiry_seconds:
                    await self._cancel(fresh['client_id'])
            for p in self.portfolio.positions():
                if not self._owned_position(p.id):
                    self.halt('UNOWNED_POSITION_NO_AUTOMATIC_ACTION')
                    continue
                if p.stop_id:
                    parent = self._owned_order(p.stop_id, 'STOP')
                    if not parent or parent['position_id'] != p.id:
                        self.halt('UNOWNED_STOP_NO_AUTOMATIC_ACTION')
                        continue
                    try:
                        stop = await self._bridge_call('query_stop', symbol=p.symbol, client_id=p.stop_id)
                        if stop and (stop.get('clientAlgoId') != p.stop_id or stop.get('symbol') != p.symbol):
                            self.halt('STOP_IDENTITY_MISMATCH_NO_IMPORT')
                            continue
                        if stop and stop.get('actualOrderId') and str(stop['actualOrderId']) != '0':
                            # The child was not submitted under a client ID in our bridge
                            # journal. Do not turn its bare exchange ID into import authority.
                            self.halt('NATIVE_STOP_CHILD_RECONCILIATION_NOT_ACCEPTED')
                            self.notify('api_error', position_id=p.id, operation='native_stop_child',
                                        message='Child-order recovery needs a separately accepted ownership protocol')
                            continue
                        elif not stop or stop.get('algoStatus') not in ('NEW', 'WORKING'):
                            p.stop_status = 'FAILED'
                            self.portfolio.save_position(p)
                            self.halt('NATIVE_STOP_NOT_ACTIVE')
                            await self._close_unlocked(p, 'stop_missing')
                    except BridgeError as error:
                        self.halt('PROTECTION_RECONCILIATION_UNKNOWN')
                        self.notify('api_error', message=str(error), position_id=p.id)
                else:
                    await self._protect(p.id)
            for oid in list(self.portfolio.get_meta('fee_pending_orders', {})):
                if self._owned_order(oid):
                    await self._reconcile_fees(oid)
                else:
                    self.halt('UNOWNED_FEE_RECORD_NO_IMPORT')
            await self.refresh_account()
